export interface Departamento {
  nombre: string;
  codigo: string;
}

export const DEPARTAMENTOS: Departamento[] = [
  { nombre: "Valle del Cauca", codigo: "VC" },
  { nombre: "Bogotá D.C.", codigo: "DC" },
  { nombre: "Antioquia", codigo: "AN" },
  { nombre: "Atlántico", codigo: "AT" },
  { nombre: "Bolívar", codigo: "BL" },
  { nombre: "Boyacá", codigo: "BY" },
  { nombre: "Caldas", codigo: "CL" },
  { nombre: "Caquetá", codigo: "CA" },
  { nombre: "Casanare", codigo: "CS" },
  { nombre: "Cauca", codigo: "CU" },
  { nombre: "Cesar", codigo: "CE" },
  { nombre: "Chocó", codigo: "CH" },
  { nombre: "Córdoba", codigo: "CO" },
  { nombre: "Cundinamarca", codigo: "CN" },
  { nombre: "Huila", codigo: "HU" },
  { nombre: "La Guajira", codigo: "LG" },
  { nombre: "Magdalena", codigo: "MA" },
  { nombre: "Meta", codigo: "ME" },
  { nombre: "Nariño", codigo: "NA" },
  { nombre: "Norte de Santander", codigo: "NS" },
  { nombre: "Putumayo", codigo: "PU" },
  { nombre: "Quindío", codigo: "QU" },
  { nombre: "Risaralda", codigo: "RI" },
  { nombre: "San Andrés y Providencia", codigo: "SA" },
  { nombre: "Santander", codigo: "SN" },
  { nombre: "Sucre", codigo: "SU" },
  { nombre: "Tolima", codigo: "TO" },
  { nombre: "Amazonas", codigo: "AM" },
  { nombre: "Arauca", codigo: "AR" },
  { nombre: "Guainía", codigo: "GU" },
  { nombre: "Guaviare", codigo: "GA" },
  { nombre: "Vaupés", codigo: "VA" },
  { nombre: "Vichada", codigo: "VI" }
];

export const MUNICIPIOS_POR_DEPARTAMENTO: Record<string, string[]> = {
  VC: ["Cali", "Palmira", "Buenaventura", "Tulua", "Buga", "Cartago", "Jamundi", "Yumbo", "Zarzal", "Florida", "Pradera", "Candelaria"],
  DC: ["Bogota"],
  AN: ["Medellin", "Bello", "Itagui", "Envigado", "Rionegro", "Apartado", "Sabaneta", "Copacabana", "La Estrella", "Caldas", "Turbo", "Caucasia", "Marinilla"],
  AT: ["Barranquilla", "Soledad", "Malambo", "Sabanagrande", "Baranoa", "Puerto Colombia", "Galapa"],
  BL: ["Cartagena", "Magangue", "Turbaco", "Arjona", "Carmen de Bolivar"],
  BY: ["Tunja", "Duitama", "Sogamoso", "Chiquinquira", "Villa de Leyva"],
  CL: ["Manizales", "La Dorada", "Chinchina", "Riosucio", "Villamaria"],
  CA: ["Florencia", "San Vicente del Caguan"],
  CS: ["Yopal", "Aguazul", "Tauramena"],
  CU: ["Popayan", "Santander de Quilichao", "Puerto Tejada", "Patia"],
  CE: ["Valledupar", "Aguachica", "Agustin Codazzi", "Bosconia"],
  CH: ["Quibdo", "Istmina"],
  CO: ["Monterian", "Cerete", "Lorica", "Sahagun", "Montelibano", "Planeta Rica"],
  CN: ["Soacha", "Facatativa", "Chia", "Zipaquira", "Fusagasuga", "Girardot", "Mosquera", "Madrid", "Funza", "Cajica", "Tocancipa", "Sopo", "Cota"],
  HU: ["Neiva", "Pitalito", "Garzon", "La Plata"],
  LG: ["Riohacha", "Maicao", "Uribia", "San Juan del Cesar"],
  MA: ["Santa Marta", "Cienaga", "Fundacion", "El Banco"],
  ME: ["Villavicencio", "Acacias", "Granada", "Puerto Lopez"],
  NA: ["Pasto", "Tumaco", "Ipiales", "Tuquerres"],
  NS: ["Cucuta", "Ocaña", "Villa del Rosario", "Los Patios", "Pamplona"],
  PU: ["Mocoa", "Puerto Asis", "Orito"],
  QU: ["Armenia", "Calarca", "Montenegro", "Quimbaya", "Tebaida"],
  RI: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"],
  SA: ["San Andres", "Providencia"],
  SN: ["Bucaramanga", "Floridablanca", "Giron", "Piedecuesta", "Barrancabermeja", "San Gil", "Socorro", "Barbosa"],
  SU: ["Sincelejo", "Corozal", "San Marcos"],
  TO: ["Ibague", "Espinal", "Melgar", "Mariquita", "Honda", "Libano"],
  AM: ["Leticia"],
  AR: ["Arauca", "Tame", "Saravena"],
  GU: ["Inirida"],
  GA: ["San Jose del Guaviare"],
  VA: ["Mitu"],
  VI: ["Puerto Carreño"]
};
